### PR TITLE
Fix libarchive352 compatibility

### PR DESCRIPTION
**Pull request by cielavenir**
this is related to https://github.com/cielavenir/miniarc/commit/80d1406a7c41c2b626fa48137cb19cd31084ccda

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks, this is great, we are not stuck at an old version now. Can I ask how you came upon this? Are you using the rwinlib static libraries for your project?

**Comment by cielavenir** [comment]
- there was a short discussion in https://twitter.com/elahieh/status/1496282396840587266 , (when released) libarchive 3.6.1 will fix 7z PPMD decompression (fixed by me), so I'd like r-lib updated as well
- for archive_entry_copy_stat thing, I found it independently while investigating system32\archiveint.dll (as a part of miniarc, mentioned above)

**Comment by gaborcsardi** [comment]
@jeroen Maybe we could try to update to 3.6.1 when it comes out? If that works then I can tell CRAN to also update to that.

**Comment by jeroen** [comment]
This this also solve the problem described here? https://github.com/r-devel/r-dev-web/blob/master/WindowsBuilds/winutf8/ucrt3/toolchain_libs/mxe/src/libarchive.mk#L8-L14

**Comment by gaborcsardi** [comment]
Yeah, that's the same thing.

**Comment by gaborcsardi** [comment]
Sure, np, I set up a watch for their releases.

**Comment by gaborcsardi** [comment]
For the record, PR is here: https://github.com/r-windows/rtools-packages/pull/253

**Pull request merged**
